'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class MyResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ResourcePack.TH07.MyResource", GetType(MyResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0000() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0000", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0001() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0001", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0002() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0002", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0003() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0003", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0004() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0004", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0100() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0100", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0101() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0101", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0102() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0102", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0103() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0103", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0104() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0104", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0105() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0105", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0106() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0106", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0200() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0200", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0201() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0201", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0300() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0300", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0400() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0400", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0401() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0401", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0402() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0402", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0403() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0403", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0404() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0404", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0405() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0405", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0406() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0406", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0407() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0407", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0408() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0408", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0500() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0500", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0501() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0501", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0502() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0502", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0503() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0503", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0700() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0700", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0701() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0701", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0702() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0702", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0703() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0703", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0704() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0704", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0705() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0705", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0706() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0706", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0707() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0707", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0708() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0708", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0800() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0800", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0801() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0801", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0802() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0802", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0803() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0803", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property boss0804() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("boss0804", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_continue() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_continue", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_continue_b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_continue_b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_quit() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_quit", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_quit_b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_quit_b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_replay() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_replay", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_replay_b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_replay_b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_retry() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_retry", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_retry_b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_retry_b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_start() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_start", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_start_b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_start_b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_title() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_title", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property bt_title_b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_title_b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property circle_blue() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("circle_blue", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property circle_cyan() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("circle_cyan", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property circle_magenta() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("circle_magenta", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property circle_red() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("circle_red", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0101a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0101a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0101b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0101b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0201a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0201a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0201b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0201b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0202a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0202a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0202b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0202b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0301a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0301a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0301b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0301b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0302a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0302a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0302b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0302b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0401a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0401a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0401b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0401b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0501a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0501a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0501b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0501b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0502a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0502a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0502b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0502b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0601a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0601a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0601b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0601b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0602a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0602a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property dialog0602b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog0602b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ding() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ding", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property game_background() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("game_background", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0000() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0000", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0100() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0100", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0101() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0101", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0102() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0102", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0103() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0103", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0200() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0200", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0201() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0201", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0202() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0202", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0203() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0203", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0400() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0400", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0401() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0401", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0402() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0402", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0403() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0403", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0500() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0500", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration0501() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration0501", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1100() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1100", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1101() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1101", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1102() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1102", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1103() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1103", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1104() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1104", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1105() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1105", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1200() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1200", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1201() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1201", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1202() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1202", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1203() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1203", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1204() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1204", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property illustration1205() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("illustration1205", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st01a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st01a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st01b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st01b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st01c() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st01c", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st02a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st02a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st02b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st02b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st02c() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st02c", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st03a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st03a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st03b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st03b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st04a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st04a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st04b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st04b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st04c() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st04c", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st04d() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st04d", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st04e() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st04e", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st04f() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st04f", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st04g() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st04g", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st05a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st05a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st06a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st06a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st06b() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st06b", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property st06c() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("st06c", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property stg5bg2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("stg5bg2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_01() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_01", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_02() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_02", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_03() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_03", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_04() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_04", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_05() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_05", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_06() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_06", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_07() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_07", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_08() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_08", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_09() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_09", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_10() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_10", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_11() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_11", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_12() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_12", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property th07_13() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("th07_13", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property title_bk00() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("title_bk00", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property words0() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("words0", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property words1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("words1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property words2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("words2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property words3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("words3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Class
End Namespace
