name=LilyTDS3
version=0.1.0
author=AGANG
maintainer=AGANG <mcagang@qq.com>
sentence=Library for LilyGo T-Display S3
paragraph=See more on www.agang.org
category=Device Control
url=
architectures=esp32
includes=LilyTDS3.h
